config/routes.rb
Rails.application.routes.draw do

  resources :dashboard
  resources :social_users
  resources :api_keys
  resources :comments
  resources :conversations, only: [:index, :show, :destroy] do
    post :mark_as_read, on: :member
    get :mark_all_as_read, on: :collection
  end
  resources :delayed_jobs
  resources :thing_categories
  resources :wizard
  resources :public_activity
  resources :thing_contacts
  resources :thing_parts
  resources :things do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end

  namespace :dynamic_select do
    get ':thing_id/thing_contacts', to: 'thing_contacts#index', as: 'thing_contacts' # el as: es para que el helper method sea 'dynamic_select_thing_contacts_path' y no 'dynamic_select_path'
  end

  namespace :dev do
    resources :catalog_cleaners do
      post :run_cleaner, on: :collection
    end
    resources :chucky_bots
    resources :examples do
      collection do
        get 'chartkick'
        get 'cors'
      end

    end
  end

  namespace :admin do
    root to: 'application#index'
    resources :settings
  end

  devise_for :users
  resources :users do
    get 'resend_password_instructions/:id', action: 'resend_password_instructions', on: :collection
    get 'mentionables', on: :collection
  end

  devise_for :api_users, controllers: { registrations: 'api_users/registrations', confirmations: 'api_users/confirmations', passwords: 'api_users/passwords' }
  resources :api_users do
    get 'error_when_confirmation', to: 'api_users/welcome#error_when_confirmation', on: :collection
    get 'check_credentials', to: 'api_users/welcome#check_credentials', on: :collection
  end
  get 'api_user_root', to: 'api_users/welcome#welcome'

  get "application/access_denied"

  get 'welcome/prueba'

  root to: 'dashboard#index'

  api_version(:module => "V1", :path => {:value => "v1"}, :defaults => {:format => "json"}) do
    resources :things
    resources :project_activity_obras
    resources :verifications
    resources :portal do
      collection do
        get :total_budget
        get :budget_by_chapter
        get :treemap
        get :suppliers
        get :mapa_obras
        get :financial_documents
        get :open_data
      end
    end
  end

  api_version(:module => "V2", :path => {:value => "v2"}, :defaults => {:format => "json"}) do
    resources :things
    resources :project_activity_obras
    resources :verifications
    resources :portal do
      collection do
        get 'total_budget/:year', action: 'total_budget'
        get :budget_by_chapter
        get 'treemap/:year', action: 'treemap'
        get 'suppliers/:year', action: 'suppliers'
        get 'mapa_obras/:year', action: 'mapa_obras'
        get 'financial_documents/:year', action: 'financial_documents'
        get :open_data
      end
    end
  end

end

app/models/thing_category.rb
class ThingCategory < ActiveRecord::Base
  has_many :things, dependent: :restrict_with_error

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/thing_categories_controller.rb
class ThingCategoriesController < ApplicationController
  load_and_authorize_resource except: :index, param_method: :thing_category_params

  # GET /thing_categories
  def index
    @thing_categories = indexize(ThingCategory)
  end

  # GET /thing_categories/1
  def show
  end

  # GET /thing_categories/new
  def new
  end

  # GET /thing_categories/1/edit
  def edit
  end

  # POST /thing_categories
  def create
    if @thing_category.save
      redirect_to @thing_category, notice: t("simple_form.flash.successfully_created") if request.format != :js
    else
      if request.format == :js # esto es por si viene creado desde un modal via ajax de otra entidad (desde Thing en este caso)
        @html_form = render_to_string('_form_remote.html.erb', layout: false, formats: [:html] )
        render :new, formats: [:js]
      else
        generate_flash_msg_no_keep(@thing_category)
        render :new
      end
    end
  end

  # PATCH/PUT /thing_categories/1
  def update
    if @thing_category.update(thing_category_params)
      redirect_to @thing_category, notice: t("simple_form.flash.successfully_updated")
    else
      generate_flash_msg_no_keep(@thing_category)
      render :edit
    end
  end

  # DELETE /thing_categories/1
  def destroy
    if @thing_category.destroy
      redirect_to thing_categories_url, notice: t("simple_form.flash.successfully_destroyed")
    else
      generate_flash_msg(@thing_category)
      redirect_to :back
    end
  end

  private

    # Only allow a trusted parameter "white list" through.
    def thing_category_params
      params.require(:thing_category).permit(:name)
    end
end

app/helpers/thing_categories_helper.rb
module ThingCategoriesHelper
end

app/views/thing_categories/_form.html.erb
<div id="wid-id-0" data-widget-colorbutton="false" data-widget-deletebutton="false" data-widget-editbutton="false" data-widget-togglebutton="false" class="jarviswidget jarviswidget-color-darken">
  <header>
    <h2><%= creating? ? "<i class='fa fa-file'></i>".html_safe : "<i class='fa fa-pencil'></i>".html_safe %></h2>
  </header>
  <div>
    <div class="widget-body">
      <%= simple_form_for @thing_category, html: { class: 'form-horizontal' },
                          wrapper: :horizontal_form,
                          wrapper_mappings: {
                                  check_boxes: :horizontal_radio_and_checkboxes,
                                  radio_buttons: :horizontal_radio_and_checkboxes,
                                  file: :horizontal_file_input,
                                  boolean: :horizontal_boolean
                          } do |f| %>
          <div class="form-inputs edit">
                                    <%= f.input :name %>
                
            <div class="widget-footer">
              <div class="form-actions">
                <div class="btn-group">
                  <%= link_to raw("<i class='fa fa-arrow-left'></i> #{t('simple_form.buttons.list')}"), thing_categories_path, class: 'btn btn-default btn-sm' if can?(:read, ThingCategory) %>
                  <%= link_to raw("<i class='fa fa-binoculars'></i> #{t('simple_form.buttons.show')}"), @thing_category, class: 'btn btn-default btn-sm' if can?(:read, ThingCategory) && updating? %>
                  <%= link_to raw("<i class='fa fa-trash'></i> #{t('simple_form.buttons.destroy')}"), @thing_category, class: 'btn btn-default btn-sm', method: :delete, data: {confirm: t('helpers.messages.are_you_sure'), 'original-title': 'Destroy'} if can?(:destroy, ThingCategory) && updating? %>
                  <button type="submit" class="btn btn-primary btn-sm"><i class='fa fa-check-circle'></i> <%= creating? ? t('simple_form.buttons.create') : t('simple_form.buttons.update') %></button>
                </div>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/thing_categories/_form_remote.html.erb
<div class="modal-dialog">
  <!-- Modal content-->
  <div class="modal-content">
    <div class="modal-header" style="background: #404040; border-radius: 4px 4px 0 0; color: #FFFFFF">
      <button type="button" class="close" data-dismiss="modal" style="color: #FFFFFF; text-shadow: 0 1px 0 #FFF;">&times;</button>
      <!-- <h4><span class="fa fa-plus"></span> Thing Category</h4> -->
      <h1 class="page-title" style="margin:0px">
        <i class="<%= t("activerecord.models.thing_category.fa_icon", default: '') %>"></i>
        <%= t("activerecord.models.thing_category.one") %> <span style="color:#CACACA">> <%= t("activerecord.actions.new") %> </span>
      </h1>
    </div>
    <%= simple_form_for @thing_category || locals[:instance], html: {class: 'form-horizontal'}, remote: true,
                        wrapper: :horizontal_form,
                        wrapper_mappings: {
                                check_boxes: :horizontal_radio_and_checkboxes,
                                radio_buttons: :horizontal_radio_and_checkboxes,
                                file: :horizontal_file_input,
                                boolean: :horizontal_boolean
                        } do |f| %>
        <div class="modal-body" style="padding:40px 50px;">
          <div class="form-inputs">
            <%= f.input :name %>
          </div>
        </div>
        <div class="modal-footer">
          <div class="btn-group">
            <a class="btn btn-default btn-sm" href="#" data-dismiss="modal"><i class="fa fa-cancel"></i> <%= t('simple_form.buttons.cancel') %>
            </a>
            <button type="submit" class="btn btn-primary btn-sm">
              <i class='fa fa-check-circle'></i> <%= t('simple_form.buttons.create') %></button>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/thing_categories/create.js.erb
$('.modal').modal('hide');
//esto seria el codigo para el ejemplo con el select 2
$('#thing_thing_category_id').select2('data', {id:<%= @thing_category.id %>, text:'<%= @thing_category.name %>'});

//esto seria el codigo para el ejemplo con el select común
//$('#thing_thing_category_id').append('<option value="<%= @thing_category.id %>" selected="selected"><%= @thing_category.name %></option>');

app/views/thing_categories/edit.html.erb
<%= render 'form' %>

app/views/thing_categories/index.html.erb
<section id="widget-grid">
  <div class="row">
    <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <div id="wid-id-0" data-widget-colorbutton="false" data-widget-deletebutton="false" data-widget-editbutton="false" data-widget-togglebutton="false" class="jarviswidget jarviswidget-color-darken">
        <header><span class="widget-icon"><i class="fa fa-table"></i></span>

          <div class="widget-toolbar filter-group">
            <%= link_to raw("<i class='fa fa-file'></i> #{t('simple_form.buttons.new')}"), new_thing_category_path, class: 'btn btn-primary' if (can? :create, ThingCategory) %>
            <a href="javascript:void(0)" data-target="#filter-wid-id-0" id="filtrar" role="button" class="filter-button btn  <%= @filter_active ? 'btn-danger' : 'btn-primary' %>"><i class="fa fa-filter"></i> <%= @filter_active ? t('simple_form.buttons.filtering') : t('simple_form.buttons.filters') %>
            </a>
          </div>
        </header>
        <div class="no-padding">
          <div class="jarviswidget-editbox filter-zone" id="filter-wid-id-0" style="display:none;">
            <div class="col-md-9 col-sm-12 no-padding"><%= search_form_for(@q, html: {name: 'filter_form', class: 'form-inline'}) do |f| %>
                  <fieldset>
                    <div class="form-group">
                      <label for="q[name_cont]"><%= t('simple_form.labels.defaults.name') %></label>
                      <%= f.search_field :name_cont, label: false, class: "form-control input-sm" %>
                    </div>
                    <div class="btn-group">
                      <button id="search_clear" name="search_clear" type="submit" value="true" class="btn btn-sm btn-warning form-control">
                        <i class="fa fa-repeat"></i> <%= t('simple_form.buttons.reset_filters') %></button>
                      <button type="submit" class="btn btn-sm btn-primary form-control">
                        <i class="fa fa-filter"></i> <%= t('simple_form.buttons.filter') %></button>
                    </div>
                  </fieldset>
              <% end %>
            </div>
          </div>
          <div class="widget-body">
            <table id="dt_basic" width="100%" class="display table table-striped table-bordered table-hover" style="margin:0 padding-top:0px">
              <thead>
              <tr>
                <th class='all control'><%= sort_link(@q, :name, t('simple_form.labels.defaults.name')) %></th>
                <th class="all"><%= t('simple_form.screen.actions') %></th>
              </tr>
              </thead>
              <tbody>
              <% @thing_categories.each do |thing_category| %>
                  <tr>
                    <td><%= thing_category.name %></td>
                    <td class="table-actions">
                      <%= render 'shared/action_icons', locals: {target: thing_category, model_edit_path: edit_thing_category_path(thing_category)} %>
                    </td>
                  </tr>
              <% end %>
              </tbody>
            </table>
            <div class="widget-footer">
              <%= render 'shared/pagination', locals: {target: @thing_categories, model_index_path: thing_categories_path} %>
            </div>
          </div>
        </div>
      </div>
    </article>
  </div>
</section>

app/views/thing_categories/new.html.erb
<%= render 'form' %>

app/views/thing_categories/new.js.erb
$("#modal-form-1").html('<%= escape_javascript(@html_form) %>');

app/views/thing_categories/show.html.erb
<section id="widget-grid">
  <article class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
    <div id="wid-id-0" data-widget-colorbutton="false" data-widget-deletebutton="false" data-widget-editbutton="false" data-widget-togglebutton="false" class="jarviswidget jarviswidget-color-darken">
      <header><span class="widget-icon"><i class="fa fa-binoculars"></i></span>
        <div class="widget-toolbar">
          <%= link_to raw("<i class='fa fa-arrow-left'></i> #{t('simple_form.buttons.list')}"), thing_categories_path, class: 'btn btn-primary' %>
          <%= link_to raw("<i class='fa fa-pencil'></i> #{t('simple_form.buttons.edit')}"), edit_thing_category_path(@thing_category), class: 'btn btn-primary' if can?(:update, ThingCategory) %>
        </div>
      </header>
      <div>
        <!-- widget content -->
        <div class="widget-body">

        <table class="table table-striped table-hover grey-blue-table" width="100%" cellspacing="0" id="dt_basic">
            <thead><tr class="hidden"><th></th><th></th></tr></thead> <!-- el thead es necesario para que datatable no de error --> <tbody>
                                        <tr role="row">
              <th><%= t('simple_form.labels.name') %></th>
              <td>
                                    <%= @thing_category.name %>
                              </td>
            </tr>
                        </tbody>
          </table>
        </div>
      </div>
    </div>
  </article>

  <!--
  <article class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
    <div id="wid-id-1" data-widget-colorbutton="false" data-widget-deletebutton="false" data-widget-editbutton="false" data-widget-togglebutton="false" class="jarviswidget jarviswidget-color-darken">
      <header><span class="widget-icon"><i class="fa fa-info"></i></span>
        <h2>Details</h2>
      </header>
      <div class="no-padding">
        <div class="widget-body">

        </div>
      </div>
    </div>
  </article>
  -->
</section>