config/routes.rb
Rails.application.routes.draw do

  resources :dashboard
  resources :social_users
  resources :api_keys
  resources :comments
  resources :conversations, only: [:index, :show, :destroy] do
    post :mark_as_read, on: :member
    get :mark_all_as_read, on: :collection
  end
  resources :delayed_jobs
  resources :thing_categories
  resources :wizard
  resources :public_activity
  resources :thing_contacts
  resources :thing_parts
  resources :things do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end

  namespace :dynamic_select do
    get ':thing_id/thing_contacts', to: 'thing_contacts#index', as: 'thing_contacts' # el as: es para que el helper method sea 'dynamic_select_thing_contacts_path' y no 'dynamic_select_path'
  end

  namespace :dev do
    resources :catalog_cleaners do
      post :run_cleaner, on: :collection
    end
    resources :chucky_bots
    resources :examples do
      collection do
        get 'chartkick'
        get 'cors'
      end

    end
  end

  namespace :admin do
    root to: 'application#index'
    resources :settings
  end

  devise_for :users
  resources :users do
    get 'resend_password_instructions/:id', action: 'resend_password_instructions', on: :collection
    get 'mentionables', on: :collection
  end

  devise_for :api_users, controllers: { registrations: 'api_users/registrations', confirmations: 'api_users/confirmations', passwords: 'api_users/passwords' }
  resources :api_users do
    get 'error_when_confirmation', to: 'api_users/welcome#error_when_confirmation', on: :collection
    get 'check_credentials', to: 'api_users/welcome#check_credentials', on: :collection
  end
  get 'api_user_root', to: 'api_users/welcome#welcome'

  get "application/access_denied"

  get 'welcome/prueba'

  root to: 'dashboard#index'

  api_version(:module => "V1", :path => {:value => "v1"}, :defaults => {:format => "json"}) do
    resources :things
    resources :project_activity_obras
    resources :verifications
    resources :portal do
      collection do
        get :total_budget
        get :budget_by_chapter
        get :treemap
        get :suppliers
        get :mapa_obras
        get :financial_documents
        get :open_data
      end
    end
  end

  api_version(:module => "V2", :path => {:value => "v2"}, :defaults => {:format => "json"}) do
    resources :things
    resources :project_activity_obras
    resources :verifications
    resources :portal do
      collection do
        get 'total_budget/:year', action: 'total_budget'
        get :budget_by_chapter
        get 'treemap/:year', action: 'treemap'
        get 'suppliers/:year', action: 'suppliers'
        get 'mapa_obras/:year', action: 'mapa_obras'
        get 'financial_documents/:year', action: 'financial_documents'
        get :open_data
      end
    end
  end

end

app/models/thing.rb
class Thing < ActiveRecord::Base
	acts_as_commentable
	acts_as_xlsx({columns: ['id', 'name', 'age', 'price', 'expires', 'discharged_at', 'description', 'published', 'gender', 'thing_category_id', 'thing_category.name']})
	include PublicActivity::Model
	tracked only: [:create, :update, :destroy]
	tracked owner: ->(controller, model) {controller.try(:current_user)}
	#tracked recipient: ->(controller, model) { model.xxxx }
	tracked :on => {:update => proc {|model, controller| model.changes.except(*model.except_attr_in_public_activity).keys.size > 0 }}
  tracked :parameters => {
							:attributes_changed => proc {|controller, model| model.id_changed? ? nil : model.changes.except(*model.except_attr_in_public_activity)},
							#:associations_changed => proc {|controller, model| model.id_changed? ? nil : de los que cambiaron y terminan con id, buscar el nombre anterior y posterior, luego en la vista buscar en la hash por el campo con id (ejemplo: category_id y obtener de la hash[:label_before], hash[:label_after] y hash[:show_url])},
							:model_label => proc {|controller, model| model.try(:name)}
          }

	belongs_to :user
	belongs_to :thing_category
	has_many :thing_contacts, dependent: :destroy
	has_many :thing_attaches, dependent: :destroy
	has_and_belongs_to_many :thing_parts, join_table: 'things_thing_parts'

	accepts_nested_attributes_for :thing_contacts, allow_destroy: true
	accepts_attachments_for :thing_attaches, attachment: :file, append: true
	accepts_nested_attributes_for :thing_attaches, allow_destroy: true

	validates_presence_of :name

	def except_attr_in_public_activity
		[:id, :updated_at]
	end

end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  load_and_authorize_resource except: :index, param_method: :thing_params

  # GET /things
  def index
    #@things = indexize(Thing, collection: Thing.where("price > 1"), order: :age, no_paginate: false)
    @things = indexize(Thing)

    respond_to do |format|
      format.html
      format.xlsx
    end
  end

  # GET /things/1
  def show
    @new_comment = Comment.build_from(@thing, current_user.id, '')
  end

  # GET /things/new
  def new
    Notificator.recipients_from_body('bbb')
  end

  # GET /things/1/edit
  def edit
  end

  # POST /things
  def create

    if @thing.save
      redirect_to @thing, notice: t('simple_form.flash.successfully_created')
    else
      generate_flash_msg_no_keep(@thing)
      render :new
    end
  end

  # PATCH/PUT /things/1
  def update
    if @thing.update(thing_params)
      #notify_other_user # todo: esto es una prueba de notificaciones, quitar cuando se implemente algo real
      redirect_to @thing, notice: t('simple_form.flash.successfully_updated')
    else
      generate_flash_msg_no_keep(@thing)
      render :edit
    end
  end

  # DELETE /things/1
  def destroy
    if @thing.destroy
      redirect_to things_url, notice: t("simple_form.flash.successfully_destroyed")
    else
      generate_flash_msg(@thing)
      redirect_to :back
    end
  end

  private

  # Only allow a trusted parameter "white list" through.
  def thing_params
    params.require(:thing).permit({thing_attaches_files: []}, {thing_attaches_attributes: [:_destroy, :id]}, {thing_contacts_attributes: [:_destroy, :id, :name, :field1, :field2, :field3]}, {thing_part_ids: []}, :name, :age, :price, :expires, :discharged_at, :description, :published, :gender, :thing_category_id, :user_id)
  end

  def notify_other_user
    if current_user.email == 'matias@opi.la'
      reciever = User.find_by_email('matiasrenta@gmail.com')
    else current_user.email == 'matiasrenta@gmail.com'
      reciever = User.find_by_email('matias@opi.la')
    end
    body = "#{current_user.name} modificó la cosa #{view_context.link_to(@thing.name, thing_path(@thing), class: 'display-normal')}"
    Notificator.send(current_user, [reciever, current_user], body)
    # current_user.send_message(reciever, "Lasdasjhba ajhjhsahashd jasdha prueba para texto muy largo en notificaciones, probando espacio de body en notificaciones, prueba más notificaciones", '<em class="badge padding-5 no-border-radius bg-color-blue pull-left margin-right-5"><i class="fa fa-cube fa-fw fa-1x"></i></em>')
  end

end

app/controllers/v1/things_controller.rb
class V1::ThingsController < V1::BaseController
  respond_to :json

  def index
    @things = Thing.all
    respond_with @things
  end

  def show
    respond_with Thing.find(params[:id])
  end

  def create
    respond_with Thing.create(thing_params)
  end

  def update
    respond_with Thing.update(params[:id], thing_params)
  end

  def destroy
    respond_with Thing.destroy(params[:id])
  end

  private

  # Only allow a trusted parameter "white list" through.
  def thing_params
    params.require(:thing).permit(:name, :age, :price, :expires, :discharged_at, :description, :published, :gender)
  end

end

app/controllers/v2/things_controller.rb
class V2::ThingsController < V2::BaseController
  respond_to :json

  def index
    @things = Thing.all
    respond_with @things
  end

  def show
    respond_with Thing.find(params[:id])
  end

  def create
    respond_with Thing.create(thing_params)
  end

  def update
    respond_with Thing.update(params[:id], thing_params)
  end

  def destroy
    respond_with Thing.destroy(params[:id])
  end

  private

  # Only allow a trusted parameter "white list" through.
  def thing_params
    params.require(:thing).permit(:name, :age, :price, :expires, :discharged_at, :description, :published, :gender)
  end

end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/things/_form.html.erb
<div id="wid-id-0" data-widget-colorbutton="false" data-widget-deletebutton="false" data-widget-editbutton="false" data-widget-togglebutton="false" class="jarviswidget jarviswidget-color-darken">
  <header>
    <h2><%= creating? ? "<i class='fa fa-file'></i>".html_safe : "<i class='fa fa-pencil'></i>".html_safe %></h2>
    <% if creating? %>
    <div class='widget-toolbar hidden-xs'>
      <a href='<%= new_import_things_path %>' role='button' class='btn btn-primary'>
        <i class='fa fa-upload'></i> Carga masiva
      </a>
    </div>
    <% end %>
  </header>
  <div class="widget-body">
    <%= simple_nested_form_for @thing, html: {class: 'form-horizontal'},
    wrapper: :horizontal_form,
    wrapper_mappings: {
      check_boxes: :horizontal_radio_and_checkboxes,
      radio_buttons: :horizontal_radio_and_checkboxes,
      attachment: :horizontal_file_input,
      boolean: :horizontal_boolean
      } do |f| %>

      <div class="form-inputs edit">
        <%= f.input :name, input_html: {class: 'field_with_popover_rt', data: {pop: 'popover-hover', placement: 'top', title: 'title', content: 'content', icon: 'fa fa-question'}} %>

        <!-- ejemplo de "nuevo en modal para un select2 Ajax" -->
        <%= f.association :thing_category, as: :ajax_select2, search_class: :thing_category, placeholder: 'Empiece escribiendo', input_html: {'data-s2-limit' => 10, 'data-s2-button-new' => true, 'data-s2-id-modal' => 'modal-form-1', 'data-s2-title' => 'Nueva categoría'} %>
        <!-- Select 2 Simple -->
        <%#= f.association :thing_category, as: :select2, placeholder: 'Empiece escribiendo', input_html: {'data-s2-limit' => 10, 'data-s2-button-new' => true, 'data-s2-id-modal' => 'modal-form-1', 'data-s2-title' => 'Nueva categoría'} %>
        <!-- Dropdown con icono fuera para agregar más -->
        <%#= f.association :thing_category, input_html: {class: 'field_with_tooltip_lf', 'data-title' => 'Agregar nuevo', 'data-icon' => 'fa fa-plus', 'data-id-modal' => 'modal-form-1'} %>

        <%= f.association :thing_parts, as: :ajax_select2, search_class: :thing_part, placeholder: 'Empiece escribiendo', input_html: {'data-s2-limit' => 10, 'data-s2-button-new' => true, 'data-s2-id-modal' => 'modal-form-2', 'data-s2-title' => 'Nueva parte'} %>
        <%= f.input :age %>
        <!-- <div class="col-sm-10 col-sm-offset-1"> -->
          <fieldset class="scheduler-border">
            <legend class="scheduler-border">Fieldset</legend>
            <div class="control-group">
              <%= f.input :price %>
              <%= f.input :expires, as: :string, input_html: {class: 'date-picker field_with_popover_lf', value: format_date_field(@thing.expires), 'data-pop' => 'popover-hover', 'data-placement' => 'top', 'data-title' => 'Fecha de expiración', 'data-content' => 'Introduce la fecha en que expira el elemento', 'data-icon' => 'fa fa-question'} %>
              <%= f.input :discharged_at, as: :string, hint: 'timezone: Mexico City', input_html: {class: 'datetimepicker', value: format_datetime_field(@thing.discharged_at)} %>
            </div>
          </fieldset>
        <!-- </div> -->

        <%= f.input :description, input_html: {class: 'mentions'} %>
        <%= f.input :published %>
        <%= f.input :gender, collection: ['Masculino', 'Femenino'] %>
        <%= f.association :user %>

        <%= render 'shared/dropzone_multiple', locals: {f: f, field: :thing_attaches_files, max_filesize: Sett['REFILE_S3_AVATAR_MAX_FILESIZE'].to_i} %>
        <div class="form-group">
          <label class="col-xs-12 col-sm-3 control-label" for="">Contacts</label>
          <div class="col-sm-9">
            <div class="table-responsive">
              <table id="contacts" width="100%" class="display tableAlt table-striped table-bordered table-hover no-margin" style="margin:0 padding-top:0px">
                <tr>
                  <th class="all control">name</th>
                  <th>field 1</th>
                  <th>field 2</th>
                  <th>field 3</th>
                  <th class="all"></th>
                </tr>
                <%= f.fields_for :thing_contacts, :wrapper => false do |thing_contact_form| %>
                <tr class="fields">
                  <td><%= thing_contact_form.input :name, wrapper: :clean %></td>
                  <td><%= thing_contact_form.input :field1, wrapper: :clean %></td>
                  <td><%= thing_contact_form.input :field2, wrapper: :clean %></td>
                  <td><%= thing_contact_form.input :field3, wrapper: :clean %></td>
                  <td align="center">
                    <%= thing_contact_form.link_to_remove do %>
                    <i class="fa fa-trash-o" data-original-title="<%= t('simple_form.tooltips.destroy') %>" data-placement="top" rel="tooltip"></i>
                    <% end %>
                  </td>
                </tr>
                <% end %>
              </table>
              <div class="well well-sm">
                <span class="btn bg-color-blue txt-color-white btn-xs">
                  <%= f.link_to_add raw("add <i class='fa fa-plus-square'></i>"), :thing_contacts, :data => {:target => "#contacts"} %>
                </span>
              </div>
            </div>
          </div>
        </div>
        <div class="widget-footer">
          <div class="form-actions">
            <div class="btn-group">
              <%= link_to raw("<i class='fa fa-arrow-left'></i> #{t('simple_form.buttons.list')}"), things_path, class: 'btn btn-default btn-sm' if can?(:read, Thing) %>
              <%= link_to raw("<i class='fa fa-binoculars'></i> #{t('simple_form.buttons.show')}"), @thing, class: 'btn btn-default btn-sm' if (can?(:read, Thing) && updating?) %>
              <%= link_to raw("<i class='fa fa-trash'></i> #{t('simple_form.buttons.destroy')}"), @thing, class: 'btn btn-default btn-sm', method: :delete, data: {confirm: t('helpers.messages.are_you_sure'), 'original-title': 'Destroy'} if (can?(:destroy, Thing) && updating?) %>
              <button type="submit" class="btn btn-primary btn-sm">
                <i class='fa fa-check-circle'></i> <%= creating? ? t('simple_form.buttons.create') : t('simple_form.buttons.update') %>
              </button>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
  <%= javascript_include_tag 'mentions' %>

  <!-- Modal categoria -->
  <div class="modal fade" id="modal-form-1" role="dialog" style="z-index:99999">
    <%= render 'thing_categories/form_remote', locals: {:instance => ThingCategory.new } %>
  </div>

  <!-- Modal parte -->
  <div class="modal fade" id="modal-form-2" role="dialog" style="z-index:99999">
    <%= render 'thing_parts/form_remote', locals: {:instance => ThingPart.new } %>
  </div>

app/views/things/edit.html.erb
<%= render 'form' %>

app/views/things/new.html.erb
<%= render 'form' %>

app/views/things/new_import.html.erb
<%= render 'shared/new_import', locals: {entity: Thing} %>

app/views/things/show.html.erb
<section id="widget-grid">
  <div class="row">

    <!-- Nuevo show ahora con divs, ya no existe tabla -->
    <article class="col-sm-6">
      <!-- Widget ID (each widget will need unique ID)-->
      <div id="wid-id-0" data-widget-colorbutton="false" data-widget-deletebutton="false" data-widget-editbutton="false" data-widget-togglebutton="false" class="jarviswidget jarviswidget-color-darken">
        <header>
          <span class="widget-icon"><i class="fa fa-binoculars"></i></span>
          <div class="widget-toolbar filter-group">
            <%= link_to raw("<i class='fa fa-arrow-left'></i> #{t('simple_form.buttons.list')}"), things_path, class: 'btn btn-primary' %>
            <%= link_to raw("<i class='fa fa-pencil'></i> #{t('simple_form.buttons.edit')}"), edit_thing_path(@thing), class: 'btn btn-primary' if can?(:update, Thing) %>
          </div>
        </header>
        <!-- widget div-->
        <div class="no-padding">
          <!-- widget edit box -->
          <div class="jarviswidget-editbox">
            <!-- This area used as dropdown edit box -->
          </div>
          <!-- end widget edit box -->
          <!-- widget content -->
          <div class="widget-body">

            <div class="form-group">

              <div class="row show-details">
                <label class="col-lg-3 col-md-4 control-label"><strong><%= t('simple_form.labels.defaults.name') %></strong></label>
                <div class="col-lg-9 details-data"><%= @thing.name %></div>
              </div>

              <div class="row show-details" >
                <label class="col-lg-3 col-md-4 control-label"><strong><%= t('simple_form.labels.defaults.category') %></strong></label>
                <div class="col-lg-9 details-data"><%= @thing.thing_category.try(:name) %></div>
              </div>

              <div class="row show-details" >
                <label class="col-lg-3 col-md-4 control-label"><strong><%= t('simple_form.labels.defaults.thing_parts') %></strong></label>
                <div class="col-lg-9 details-data"><%= @thing.thing_parts.map(&:name).join(', ') %></div>
              </div>

              <div class="row show-details" >
                <label class="col-lg-3 col-md-4 control-label"><strong><%= t('simple_form.labels.defaults.thing_contacts') %></strong></label>
                <div class="col-lg-9 details-data"><%= @thing.thing_contacts.map(&:name).join(', ') %></div>
              </div>

              <div class="row show-details" >
                <label class="col-lg-3 col-md-4 control-label"><strong><%= t('simple_form.labels.defaults.age') %></strong></label>
                <div class="col-lg-9 details-data"><%= @thing.age %></div>
              </div>

              <div class="row show-details" >
                <label class="col-lg-3 col-md-4 control-label"><strong><%= t('simple_form.labels.defaults.price') %></strong></label>
                <div class="col-lg-9 details-data"><%= @thing.price ? number_to_currency(@thing.price, unit: '') : nil %></div>
              </div>

              <div class="row show-details" >
                <label class="col-lg-3 col-md-4 control-label"><strong><%= t('simple_form.labels.defaults.expires') %></strong></label>
                <div class="col-lg-9 details-data"><%= l(@thing.expires, :format => :long) if @thing.expires %></div>
              </div>

              <div class="row show-details" >
                <label class="col-lg-3 col-md-4 control-label"><strong><%= t('simple_form.labels.defaults.discharged_at') %></strong></label>
                <div class="col-lg-9 details-data"><%= l(@thing.discharged_at, :format => :long) if @thing.discharged_at %></div>
              </div>

              <div class="row show-details" >
                <label class="col-lg-3 col-md-4 control-label"><strong><%= t('simple_form.labels.defaults.description') %></strong></label>
                <div class="col-lg-9 details-data">
                  <div class="mentions" contenteditable>
                    <%= @thing.description %>
                  </div>
                </div>
              </div>

              <div class="row show-details" >
                <label class="col-lg-3 col-md-4 control-label"><strong><%= t('simple_form.labels.defaults.published') %></strong></label>
                <div class="col-lg-9 details-data"><%= boolean_check_mark(@thing.published) %></div>
              </div>

              <div class="row show-details" >
                <label class="col-lg-3 col-md-4 control-label"><strong><%= t('simple_form.labels.defaults.gender') %></strong></label>
                <div class="col-lg-9 details-data"><%= @thing.gender %></div>
              </div>

              <div class="row show-details" >
                <label class="col-lg-3 col-md-4 control-label"><strong>Imágenes</strong></label>
                <div class="col-lg-9 details-data"><% @thing.thing_attaches.each do |attach| %>
                  <p class="form-control-static"><%= image_tag attachment_url(attach, :file, :fill, 100, 100) %></p>
                  <% end %>
                </div>
              </div>
            </div>

          </div>
          <!-- end widget content -->
        </div>
        <!-- end widget div -->

      </div>
      <!-- end widget -->
    </article>
    <!-- Fin nuevo show -->

  </div>
</section>

<%= render partial: "comments/template", locals: {commentable: @thing, new_comment: @new_comment} %>
<%= javascript_include_tag 'mentions' %>

<script type="text/javascript">
  $('.show-details:even').addClass('striped-div');
</script>