config/routes.rb
Rails.application.routes.draw do

  resources :dashboard
  resources :social_users
  resources :api_keys
  resources :comments
  resources :conversations, only: [:index, :show, :destroy] do
    post :mark_as_read, on: :member
    get :mark_all_as_read, on: :collection
  end
  resources :delayed_jobs
  resources :thing_categories
  resources :wizard
  resources :public_activity
  resources :thing_contacts
  resources :thing_parts
  resources :things do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end

  namespace :dynamic_select do
    get ':thing_id/thing_contacts', to: 'thing_contacts#index', as: 'thing_contacts' # el as: es para que el helper method sea 'dynamic_select_thing_contacts_path' y no 'dynamic_select_path'
  end

  namespace :dev do
    resources :catalog_cleaners do
      post :run_cleaner, on: :collection
    end
    resources :chucky_bots
    resources :examples do
      collection do
        get 'chartkick'
        get 'cors'
      end

    end
  end

  namespace :admin do
    root to: 'application#index'
    resources :settings
  end

  devise_for :users
  resources :users do
    get 'resend_password_instructions/:id', action: 'resend_password_instructions', on: :collection
    get 'mentionables', on: :collection
  end

  devise_for :api_users, controllers: { registrations: 'api_users/registrations', confirmations: 'api_users/confirmations', passwords: 'api_users/passwords' }
  resources :api_users do
    get 'error_when_confirmation', to: 'api_users/welcome#error_when_confirmation', on: :collection
    get 'check_credentials', to: 'api_users/welcome#check_credentials', on: :collection
  end
  get 'api_user_root', to: 'api_users/welcome#welcome'

  get "application/access_denied"

  get 'welcome/prueba'

  root to: 'dashboard#index'

  api_version(:module => "V1", :path => {:value => "v1"}, :defaults => {:format => "json"}) do
    resources :things
    resources :project_activity_obras
    resources :verifications
    resources :portal do
      collection do
        get :total_budget
        get :budget_by_chapter
        get :treemap
        get :suppliers
        get :mapa_obras
        get :financial_documents
        get :open_data
      end
    end
  end

  api_version(:module => "V2", :path => {:value => "v2"}, :defaults => {:format => "json"}) do
    resources :things
    resources :project_activity_obras
    resources :verifications
    resources :portal do
      collection do
        get 'total_budget/:year', action: 'total_budget'
        get :budget_by_chapter
        get 'treemap/:year', action: 'treemap'
        get 'suppliers/:year', action: 'suppliers'
        get 'mapa_obras/:year', action: 'mapa_obras'
        get 'financial_documents/:year', action: 'financial_documents'
        get :open_data
      end
    end
  end

end

app/views/shared/_action_icons.html.erb
<%= link_to raw('<i class="fa fa-binoculars fa-lg"></i>'), locals[:target], rel: 'tooltip', title: t('simple_form.tooltips.show'), data: { toggle: 'toggle', placement: 'top', 'original-title' => t('simple_form.tooltips.show')} if can? :read, locals[:target] %>
<%= link_to raw('<i class="fa fa-pencil fa-lg"></i>'), edit_model_path(locals[:target]), rel: 'tooltip', title: t('simple_form.tooltips.edit'), data: { toggle: 'toggle', placement: 'top', 'original-title' => t('simple_form.tooltips.edit')} if can? :update, locals[:target] %>
<%= link_to raw('<i class="fa fa-trash fa-lg"></i>'), locals[:target], method: :delete, rel: 'tooltip', title: t('simple_form.tooltips.destroy'), class:'tooltipwithnofollow', data: { toggle: 'toggle', placement: 'top' , confirm: t('helpers.messages.are_you_sure'), 'original-title' => t('simple_form.tooltips.destroy')} if can? :destroy, locals[:target] %>

<% if locals[:extra_actions] %>
    <% locals[:extra_actions].each do |extra_action| %>
        <!-- esto no esta programado, extra_action deberá ser un hash con todas las cosas que hagan falta para crear cualquier link -->
        <%= link_to raw("<i class='fa #{extra_action[:fa_icon]}  fa-lg'></i>"), extra_action[:url], rel: 'tooltip', data: { toggle: 'toggle', placement: 'top', 'original-title' => extra_action[:tooltip]} if can?(extra_action[:name].to_sym, locals[:target]) %>
    <% end %>
<% end %>

app/views/shared/_dropzone_multiple.html.erb
<%
  f = locals[:f]
  field = locals[:field]
  association = field.to_s.split('_files')[0].to_sym
  label = locals[:label] || t("simple_form.labels.defaults.#{association}")
  instance = f.object
  accepted_files = instance.send(association).send("file_attachment_definition").valid_content_types.join(', ') if instance.send(association).send("file_attachment_definition").valid_content_types
%>

<%= f.input field, as: :attachment, multiple: true, direct: locals[:direct] || true, label: false, input_html: {style: 'display: none;'} %>
<div class="form-group">
 <label class="col-xs-12 col-sm-3 control-label" for=""><%= label %></label>
 <div class="col-sm-8">
   <div class="upload-dropzone dropzone dz-clickable" data-upload-field="images" id="dropzoneMultiple">
     <div class="dz-default dz-message">
       <div class="col-xs-12">
         <h3><i class="fa fa-caret-right text-danger"></i> <%= t('simple_form.screen.click_or_drop_files') %>.</h3>
       </div>
     </div>
   </div>
 </div>
</div>

<%= f.fields_for association do |upload| %>
  <div class="hidden">
   <%= upload.input :_destroy, as: :boolean, wrapper: :clean, label: false, input_html: {style: 'display: none;'} %>
  </div>
<% end %>

<%= render 'shared/dropzone_shared' %>

<script type="text/javascript">
    Dropzone.options.dropzoneMultiple = {
        maxFiles: null,
        maxFilesize: <%= locals[:max_filesize] %>,
        acceptedFiles: '<%= accepted_files %>',
        dictDefaultMessage: '<%= t('simple_form.screen.click_or_drop_files') %>',
        dictFallbackMessage: '<%= t('simple_form.screen.not_support_drag_drop') %>',
        dictFallbackText: '<%= t('simple_form.screen.use_the_form_below') %>',
        dictFileTooBig: '<%= t('simple_form.screen.file_is_too_big') %> ({{filesize}}Mb). <%= t('simple_form.screen.max_filesize') %>: {{maxFilesize}}Mb.',
        dictInvalidFileType: '<%= t('simple_form.screen.cant_upload_this_type') %>',
        dictResponseError: '<%= t('simple_form.screen.server_responded_with_code') %>: {{statusCode}}',
        dictCancelUpload: '<%= t('simple_form.screen.cancel_upload') %>',
        dictCancelUploadConfirmation: '<%= t('simple_form.screen.are_you_sure_cancel_upload') %>',
        dictRemoveFile: '<%= t('simple_form.screen.remove_file') %>',
        dictRemoveFileConfirmation: null,
        dictMaxFilesExceeded: '<%= t('simple_form.screen.cant_upload_any_more_files') %>',
        init: function (file, done) {
            thisDropzone = this;
            var mockFile = {};
            var indexVar = 0;
            <%= f.fields_for association, nil, {wrapper: false, include_id: false} do |uploaded| %>
            <% f_input_string = uploaded.input :_destroy, as: :boolean, wrapper: :clean
                hidden_name = f_input_string.split('name="')[1].split('"')[0] %>
            mockFile = {
                name: '<%= uploaded.object.file_filename %>',
                size: <%= uploaded.object.file_size %>,
                type: '<%= uploaded.object.file_content_type %>',
                hidden_name: '<%= hidden_name %>',
                index: indexVar
            };
            thisDropzone.options.addedfile.call(thisDropzone, mockFile);
            thisDropzone.options.thumbnail.call(thisDropzone, mockFile, '<%= attachment_url(uploaded.object, :file, :fill, 100, 100) %>');
            noImage(mockFile);
            indexVar++;
            <% end %>
            $('#dropzoneMultiple').removeClass('dz-started');
            $('.dz-image').children().before('<i class="fileUploadedCheck fa fa-2x fa-check-circle"></i>');
            $('.dz-progress').fadeOut();
        },
        accept: function (file, done) {
            back_files_news(file, done);
        }
    };
</script>

app/views/shared/_dropzone_shared.html.erb
<script>
    var thumbnail;
    function back_files(type) {
        thumbnail = $('.dz-image:last');
        cases_background(type);
    };

    function back_files_news(file, done) {
        thumbnail = $('.dropzone .dz-preview.dz-file-preview .dz-image:last');
        cases_background(file.type);
        done();
    }

    function cases_background(type){
        switch (type) {
            case 'application/pdf':
                thumbnail.css('background', 'url(<%= image_url("dropzone/pdf-icon.png") %>)');
                break;
            case 'application/vnd.openxmlformats-officedocument.wordprocessingml.document':
                thumbnail.css('background', 'url(<%= image_url("dropzone/word-icon.png") %>)');
                break;
            case 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':
                thumbnail.css('background', 'url(<%= image_url("dropzone/xls-icon.png") %>)');
                break;
            case 'text/csv':
                thumbnail.css('background', 'url(<%= image_url("dropzone/xls-icon.png") %>)');
                break;
            default:
                thumbnail.css('background', 'url(<%= image_url("dropzone/default-file-icon.png") %>)');
                break;
        }
    }

    function noImage(mockFile){
        var thumbnail = $('.dz-image:last');
        var type = mockFile.type;
        $(thumbnail).each(function (i) {
            if (type != 'image/png' && type != 'image/jpeg' && type != 'image/jpg' && type != 'image/gif') {
                $(thumbnail).children().removeAttr('src alt');
                back_files(type);
            }
            return false;
        });
    }
</script>

app/views/shared/_dropzone_simple.html.erb
<%
  instance = locals[:f].object
  remove_hidden_name = "#{instance.class.name.underscore}[remove_#{locals[:field]}]"
  label = locals[:label] || t("simple_form.labels.defaults.#{locals[:field]}")
  accepted_files = instance.send("#{locals[:field]}_attachment_definition").valid_content_types.join(', ') if instance.send("#{locals[:field]}_attachment_definition").valid_content_types
%>
<%= locals[:f].input locals[:field], as: :attachment, direct: true, label: false, input_html: {style: 'display: none;', 'data-remove-hidden-name': remove_hidden_name} %>
<div class="form-group">
 <label class="col-xs-12 col-sm-3 control-label" for=""><%= label %></label>
 <div class="col-sm-8">
   <div class="upload-dropzone dropzone dz-clickable" data-upload-field="images" id="dropzoneSimple">
     <div class="dz-default dz-message">
       <div class="col-xs-12">
         <h3><i class="fa fa-caret-right text-danger"></i> <%= t('simple_form.screen.click_or_drop_file') %>.</h3>
       </div>
     </div>
   </div>
 </div>
</div>

<% if instance.send(locals[:field]) %>
   <%= locals[:f].input "remove_#{locals[:field]}".to_sym, as: :boolean, wrapper: :clean, input_html: {style: 'display: none;'} %>
   <script type="text/javascript">
     var file_exist = true;
   </script>
   <% else %>
     <script type="text/javascript">
       var file_exist = false;
     </script>
<% end %>

<%= render 'shared/dropzone_shared' %>

<script type="text/javascript">
    Dropzone.options.dropzoneSimple = {
        maxFiles: 1,
        maxFilesize: <%= locals[:max_filesize] %>,
        acceptedFiles: '<%= accepted_files %>',
        dictDefaultMessage: '<%= t('simple_form.screen.click_or_drop_files') %>',
        dictFallbackMessage: '<%= t('simple_form.screen.not_support_drag_drop') %>',
        dictFallbackText: '<%= t('simple_form.screen.use_the_form_below') %>',
        dictFileTooBig: '<%= t('simple_form.screen.file_is_too_big') %> ({{filesize}}Mb). <%= t('simple_form.screen.max_filesize') %>: {{maxFilesize}}Mb.',
        dictInvalidFileType: '<%= t('simple_form.screen.cant_upload_this_type') %>',
        dictResponseError: '<%= t('simple_form.screen.server_responded_with_code') %>: {{statusCode}}',
        dictCancelUpload: '<%= t('simple_form.screen.cancel_upload') %>',
        dictCancelUploadConfirmation: '<%= t('simple_form.screen.are_you_sure_cancel_upload') %>',
        dictRemoveFile: '<%= t('simple_form.screen.remove_file') %>',
        dictRemoveFileConfirmation: null,
        dictMaxFilesExceeded: '<%= t('simple_form.screen.cant_upload_any_more_files') %>',
        init: function (file, done) {
            thisDropzone = this;
            var mockFile = {};
            mockFile = {
                name: file_exist ? '<%= instance.send("#{locals[:field]}_filename".to_sym) %>' : '',
                size: file_exist ? '<%= instance.send("#{locals[:field]}_size".to_sym) %>' : '',
                type: file_exist ? '<%= instance.send("#{locals[:field]}_content_type".to_sym) %>' : '',
                hidden_name: file_exist ? '<%= remove_hidden_name %>' : ''
            };
            if (file_exist) {
                thisDropzone.options.addedfile.call(thisDropzone, mockFile);
            }
            thisDropzone.options.thumbnail.call(thisDropzone, mockFile, '<%= attachment_url(instance, locals[:field], :fill, 100, 100) %>');
            noImage(mockFile);
            $('#dropzoneSimple').removeClass('dz-started');
            $('.dz-image').children().before('<i class="fileUploadedCheck fa fa-2x fa-check-circle"></i>');
            $('.dz-progress').fadeOut();
        },
        accept: function (file, done) {
            back_files_news(file, done);
        }
    }
</script>

app/views/shared/_flash_messages.html.erb
<article class="col-sm-12">
  <% if alert %>
      <div class="alert alert-danger fade in">
        <button class="close" data-dismiss="alert">
          ×
        </button>
        <i class="fa-fw fa fa-ban fa-2x"></i>
        <strong><%= alert %></strong>
      </div>
  <% end %>

  <% if flash[:warning] %>
      <div class="alert alert-warning fade in">
        <button class="close" data-dismiss="alert">
          ×
        </button>
        <i class="fa-fw fa fa-warning fa-2x"></i>
        <strong><%= flash[:warning] %></strong>
      </div>
  <% end %>

  <% if flash[:info] %>
      <div class="alert alert-info fade in">
        <button class="close" data-dismiss="alert">
          ×
        </button>
        <i class="fa-fw fa fa-info-circle fa-2x"></i>
        <strong><%= flash[:info] %></strong>
      </div>
  <% end %>

  <% if notice && notice != 'Has iniciado sesión correctamente.' %>
      <div class="alert alert-success fade in">
        <button class="close" data-dismiss="alert">
          ×
        </button>
        <i class="fa-fw fa fa-check fa-2x"></i>
        <strong><%= notice %></strong>
      </div>
  <% end %>

</article>

app/views/shared/_new_import.html.erb
<%
   entity = locals[:entity]
   parent_entity = locals[:parent_entity] # si el entity está como nested resource se debe armar la url distinto
   nested_string = ''
   nested_string = "#{parent_entity.name.underscore}_" if parent_entity

   download_import_file_path = eval("download_import_file_#{nested_string}#{entity.name.underscore.pluralize}_path(format: :xlsx)")
   create_import_path = eval("create_import_#{nested_string}#{entity.name.underscore.pluralize}_path")
   new_entity_path = eval("new_#{nested_string}#{entity.name.underscore}_path")#'/things/new'
   i18n_entity_other = "activerecord.models.#{entity.name.underscore}.other"
   i18n_entity_one = "activerecord.models.#{entity.name.underscore}.one"
%>

<section id="widget-grid">

	<!-- row -->
	<div class="row">
		<!-- NEW WIDGET START -->
		<article class="col-sm-8">

			<div id="wid-id-0" data-widget-colorbutton="false" data-widget-deletebutton="false" data-widget-editbutton="false" data-widget-togglebutton="false" data-widget-fullscreenbutton="false" class="jarviswidget jarviswidget-color-darken">

				<header>
					<span class="widget-icon"><i class='fa fa-upload'></i></span>
				</header>

				<div class="widget-body">
					<p>
						Para lograr una correcta importación se recomienda descargar el archivo xslx a continuación. Este archivo servirá como plantilla, ya que contiene las columnas adecuadas que requiere el sistema. Es importante no modificar el formato ni agregar datos innecesarios para así evitar un error en la importación.
					</p>
					<div class="btn-toolbar pull-right">
						<%= link_to 'Download import file', download_import_file_path, :class =>'btn btn-primary' %>
					</div>
					<br><br><hr>
					<!-- <h5>Seleccionar archivo para importar:</h5> -->
					<p>
						Una vez que tenga su archivo xlsx con los registros en cada columna, seleccionelo desde su equipo y oprima el botón Importar.
					</p>
					<br>
					<%= form_for @entity_import, url: create_import_path do |f| %>
					<%= f.file_field :file %>
					<div class="row">
						<br><br><br>
						<div class="col-sm-6">
							<i class="fa fa-fw fa-list-ul text-warning"></i> Cantidad de registros: <%= f.select :quantity_records, [['Un par para probar', 'un_par'], ['Todos', 'todos']] %>
						</div>
						<div class="col-sm-6">
							<i class="fa fa-fw fa-database text-primary"></i> Grabar en ddbb: <%= f.check_box :save_in_ddbb %>
						</div>
						<br><br><br>
					</div>
					<div class="btn-toolbar pull-right">
						<a href="<%= new_entity_path %>" type="button" class="btn btn-default">Back</a>
						<%= f.submit "Import", :class =>'btn btn-primary' %>
					</div>
					<br><br><br>
				</div>

			</div><!-- End jarvis -->

		</article>

		<div class="col-sm-4">
			<div class="well well-light">
				<h5>Datos informativos:</h5>
				<hr>
				<ul class="list-unstyled" style="line-height: 3;">
					<li>
						<i class="fa fa-fw fa-th-list text-success"></i> Cantidad de <%= t(i18n_entity_other) %>: <%= entity.count %>
					</li>
					<li>
						<i class="fa fa-fw fa-slack text-danger"></i> Maximum <%= t(i18n_entity_one) %> ID: <%= entity.maximum(:id) %>
					</li>
				</ul>
			</div>
		</div>

	</div>
	<% end %>
</section>

app/views/shared/_pagination.html.erb
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <div class="col-lg-4 col-lg-offset-7 col-md-9 col-md-offset-2 col-sm-9 col-sm-offset-2 col-xs-10">
     <%= will_paginate locals[:target], inner_window: 1, outer_window: 1, renderer: BootstrapPagination::Rails, class: 'no-margin pagination-xs' %>
  </div>
  <div class="col-lg-1 col-md-1 col-sm-1 col-xs-2 no-padding">
    
     <%= form_tag locals[:model_index_path], id: 'per_page_change', method: 'get' do %>
      <%= select_tag :per_page, options_for_select([1, 2, 5, 10, 20, 50, 100], params[:per_page]), {class: "form-control input-xs", onchange: "this.form.submit();"} %>
    <% end %>
   
   
  </div>
</div>

app/views/shared/_show_financial_doc_in_project_activity.html.erb
<article class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
  <div id="wid-id-1" data-widget-colorbutton="false" data-widget-deletebutton="false" data-widget-editbutton="false" data-widget-togglebutton="false" class="jarviswidget jarviswidget-color-darken">
    <header>
      <span class="widget-icon"><i class="fa fa-file-pdf-o"></i></span>
      <h2>Documentos Financieros</h2>
      <div class="widget-toolbar">
        <%= link_to raw("<i class='fa fa-file'></i> #{t('simple_form.buttons.new')}"), locals[:new_path], class: 'btn btn-primary' if can?(:create, FinancialDocument.new(project_activityable: locals[:instance])) %>
      </div>
    </header>
    <div class="no-padding">
      <div class="widget-body">
        <table id="dt_basic" width="100%" class="display table table-striped table-bordered table-hover">
          <thead>
          <tr>
            <th class='all control'>Tipo</th>
            <th>Número</th>
            <th>Importe</th>
            <th class="all"><%= t('simple_form.screen.actions') %></th>
          </tr>
          </thead>
          <tbody>
          <% locals[:instance].financial_documents.each do |fd| %>
              <tr>
                <td><%= fd.financial_document_type.try(:name) %></td>
                <td><%= fd.nro_documento %></td>
                <td><%= fd.monto %></td>
                <td class="table-actions">
                  <%= link_to raw('<i class="fa fa-binoculars fa-lg"></i>'), financial_document_path(fd), rel: 'tooltip', title: t('simple_form.tooltips.show'), data: { toggle: 'toggle', placement: 'top', 'original-title' => t('simple_form.tooltips.show')} if can? :read, fd %>
                  <%= link_to raw('<i class="fa fa-pencil fa-lg"></i>'), edit_financial_document_path(fd), rel: 'tooltip', title: t('simple_form.tooltips.edit'), data: { toggle: 'toggle', placement: 'top', 'original-title' => t('simple_form.tooltips.edit')} if can? :update, fd %>
                  <%= link_to raw('<i class="fa fa-trash fa-lg"></i>'), financial_document_path(fd), method: :delete, rel: 'tooltip', title: t('simple_form.tooltips.destroy'), class:'tooltipwithnofollow', data: { toggle: 'toggle', placement: 'top' , confirm: t('helpers.messages.are_you_sure'), 'original-title' => t('simple_form.tooltips.destroy')} if can? :destroy, fd %>
                </td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</article>

app/views/shared/_submit_filters.html.erb
<div class="btn-group">
  <button type="submit" class="btn btn-sm btn-primary">
    <i class="fa fa-filter"></i> <%= t('simple_form.buttons.filter') %>
  </button>
  <button id="search_clear" name="search_clear" type="submit" value="true" class="btn btn-sm btn-warning">
    <i class="fa fa-repeat"></i> <%= t('simple_form.buttons.reset_filters') %>
  </button>
</div>