config/routes.rb
Rails.application.routes.draw do

  resources :dashboard
  resources :social_users
  resources :api_keys
  resources :comments
  resources :conversations, only: [:index, :show, :destroy] do
    post :mark_as_read, on: :member
    get :mark_all_as_read, on: :collection
  end
  resources :delayed_jobs
  resources :thing_categories
  resources :wizard
  resources :public_activity
  resources :thing_contacts
  resources :thing_parts
  resources :things do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end

  namespace :dynamic_select do
    get ':thing_id/thing_contacts', to: 'thing_contacts#index', as: 'thing_contacts' # el as: es para que el helper method sea 'dynamic_select_thing_contacts_path' y no 'dynamic_select_path'
  end

  namespace :dev do
    resources :catalog_cleaners do
      post :run_cleaner, on: :collection
    end
    resources :chucky_bots
    resources :examples do
      collection do
        get 'chartkick'
        get 'cors'
      end

    end
  end

  namespace :admin do
    root to: 'application#index'
    resources :settings
  end

  devise_for :users
  resources :users do
    get 'resend_password_instructions/:id', action: 'resend_password_instructions', on: :collection
    get 'mentionables', on: :collection
  end

  devise_for :api_users, controllers: { registrations: 'api_users/registrations', confirmations: 'api_users/confirmations', passwords: 'api_users/passwords' }
  resources :api_users do
    get 'error_when_confirmation', to: 'api_users/welcome#error_when_confirmation', on: :collection
    get 'check_credentials', to: 'api_users/welcome#check_credentials', on: :collection
  end
  get 'api_user_root', to: 'api_users/welcome#welcome'

  get "application/access_denied"

  get 'welcome/prueba'

  root to: 'dashboard#index'

  api_version(:module => "V1", :path => {:value => "v1"}, :defaults => {:format => "json"}) do
    resources :things
    resources :project_activity_obras
    resources :verifications
    resources :portal do
      collection do
        get :total_budget
        get :budget_by_chapter
        get :treemap
        get :suppliers
        get :mapa_obras
        get :financial_documents
        get :open_data
      end
    end
  end

  api_version(:module => "V2", :path => {:value => "v2"}, :defaults => {:format => "json"}) do
    resources :things
    resources :project_activity_obras
    resources :verifications
    resources :portal do
      collection do
        get 'total_budget/:year', action: 'total_budget'
        get :budget_by_chapter
        get 'treemap/:year', action: 'treemap'
        get 'suppliers/:year', action: 'suppliers'
        get 'mapa_obras/:year', action: 'mapa_obras'
        get 'financial_documents/:year', action: 'financial_documents'
        get :open_data
      end
    end
  end

end

app/models/api/api_key.rb
class ApiKey < ActiveRecord::Base
  validates :application, presence: true
  validates :application, uniqueness: true

  before_create :generate_access_token

  private

  def generate_access_token
    begin
      self.access_token = SecureRandom.hex
    end while self.class.exists?(access_token: access_token)
  end

end

app/controllers/api_keys_controller.rb
class ApiKeysController < ApplicationController
  load_and_authorize_resource except: :index, param_method: :api_key_params

  # GET /api_keys
  def index
    @api_keys = indexize(ApiKey)
  end

  # GET /api_keys/1
  def show
  end

  # GET /api_keys/new
  def new
  end

  # GET /api_keys/1/edit
  def edit
  end

  # POST /api_keys
  def create

    if @api_key.save
      redirect_to @api_key, notice: t("simple_form.flash.successfully_created")
    else
      generate_flash_msg_no_keep(@api_key)
      render :new
    end
  end

  # PATCH/PUT /api_keys/1
  def update
    if @api_key.update(api_key_params)
      redirect_to @api_key, notice: t("simple_form.flash.successfully_updated")
    else
      generate_flash_msg_no_keep(@api_key)
      render :edit
    end
  end

  # DELETE /api_keys/1
  def destroy
    if @api_key.destroy
      redirect_to api_keys_url, notice: t("simple_form.flash.successfully_destroyed")
    else
      generate_flash_msg(@api_key)
      redirect_to api_keys_url
    end
  end

  private

    # Only allow a trusted parameter "white list" through.
    def api_key_params
      params.require(:api_key).permit(:application, :access_token, :access_only_with_token, :note)
    end
end

app/helpers/api_keys_helper.rb
module ApiKeysHelper
end

app/views/api_keys/_form.html.erb
<div id="wid-id-0" data-widget-colorbutton="false" data-widget-deletebutton="false" data-widget-editbutton="false" data-widget-togglebutton="false" class="jarviswidget jarviswidget-color-darken">
  <header>
    <h2><%= creating? ? "<i class='fa fa-file'></i>".html_safe : "<i class='fa fa-pencil'></i>".html_safe %></h2>
  </header>
  <div>
    <div class="widget-body">
      <%= simple_form_for @api_key, html: {class: 'form-horizontal'},
                          wrapper: :horizontal_form,
                          wrapper_mappings: {
                                  check_boxes: :horizontal_radio_and_checkboxes,
                                  radio_buttons: :horizontal_radio_and_checkboxes,
                                  file: :horizontal_file_input,
                                  boolean: :horizontal_boolean
                          } do |f| %>
          <div class="form-inputs edit">
            <%= f.input :application %>
            <%= f.input :access_only_with_token, hint: t('simple_form.hints.access_only_with_token') %>
            <%= f.input :note, :input_html => {:rows => 4, :cols => 30} %>
            <%= f.input :access_token if updating? %>

            <div class="widget-footer">
              <div class="form-actions">
                <div class="btn-group">
                  <%= link_to raw("<i class='fa fa-arrow-left'></i> #{t('simple_form.buttons.list')}"), api_keys_path, class: 'btn btn-default btn-sm' if can?(:read, ApiKey) %>
                  <%= link_to raw("<i class='fa fa-binoculars'></i> #{t('simple_form.buttons.show')}"), @api_key, class: 'btn btn-default btn-sm' if can?(:read, ApiKey) && updating? %>
                  <%= link_to raw("<i class='fa fa-trash'></i> #{t('simple_form.buttons.destroy')}"), @api_key, class: 'btn btn-default btn-sm', method: :delete, data: {confirm: t('helpers.messages.are_you_sure'), 'original-title': 'Destroy'} if can?(:destroy, ApiKey) && updating? %>
                  <button type="submit" class="btn btn-primary btn-sm">
                    <i class='fa fa-check-circle'></i> <%= creating? ? t('simple_form.buttons.create') : t('simple_form.buttons.update') %>
                  </button>
                </div>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/api_keys/edit.html.erb
<%= render 'form' %>

app/views/api_keys/index.html.erb
<section id="widget-grid">
  <div class="row">
    <article class="col-xs-12">
      <div id="wid-id-0" data-widget-colorbutton="false" data-widget-deletebutton="false" data-widget-editbutton="false" data-widget-togglebutton="false" class="jarviswidget jarviswidget-color-darken">
        <header><span class="widget-icon"><i class="fa fa-table"></i></span>

          <div class="widget-toolbar filter-group">
            <%= link_to raw("<i class='fa fa-file'></i> #{t('simple_form.buttons.new')}"), new_api_key_path, class: 'btn btn-primary' if (can? :create, ApiKey) %>
            <a href="javascript:void(0)" data-target="#filter-wid-id-0" id="filtrar" role="button" class="filter-button btn <%= @filter_active ? 'btn-danger' : 'btn-primary' %>"><i class="fa fa-filter"></i> <%= @filter_active ? t('simple_form.buttons.filtering') : t('simple_form.buttons.filters') %>
            </a>
          </div>
        </header>
        <div class="no-padding">
          <div class="jarviswidget-editbox filter-zone" id="filter-wid-id-0" style="display:none;">
            <div class="col-xs-12"><%= search_form_for(@q, html: {name: 'filter_form', class: 'form-inline'}) do |f| %>
                  <fieldset>
                    <div class="row">
                      <div class="col-md-3 col-sm-6 col-xs-12">
                        <label for="q[application_cont]"><%= t('simple_form.labels.defaults.application') %></label>
                        <%= f.search_field :application_cont, label: false, class: "form-control input-sm" %>
                      </div>
                      <div class="col-md-3 col-sm-6 col-xs-12">
                        <label for="q[access_token_cont]"><%= t('simple_form.labels.defaults.access_token') %></label>
                        <%= f.search_field :access_token_cont, label: false, class: "form-control input-sm" %>
                      </div>
                      <div class="col-md-3 col-sm-6 col-xs-12">
                        <label for="q[note_cont]"><%= t('simple_form.labels.defaults.note') %></label>
                        <%= f.search_field :note_cont, label: false, class: "form-control input-sm" %>
                      </div>
                    </div>
                    <div class="row pull-right">
                      <div class="col-sm-12">
                        <%= render 'shared/submit_filters' %>
                      </div>
                    </div>
                  </fieldset>
              <% end %>
            </div>
          </div>
          <div class="widget-body">
            <table id="dt_basic" width="100%" class="display table table-striped table-bordered table-hover" style="margin:0 padding-top:0px">
              <thead>
              <tr>
                <th class='all control'><%= sort_link(@q, :application, t('simple_form.labels.defaults.application')) %></th>
                <th><%= sort_link(@q, :access_token, t('simple_form.labels.defaults.access_token')) %></th>
                <th><%= sort_link(@q, :access_only_with_token, t('simple_form.labels.defaults.access_only_with_token')) %></th>
                <th><%= sort_link(@q, :note, t('simple_form.labels.defaults.note')) %></th>
                <th class="all"><%= t('simple_form.screen.actions') %></th>
              </tr>
              </thead>
              <tbody>
              <% @api_keys.each do |api_key| %>
                  <tr>
                    <td><%= api_key.application %></td>
                    <td><%= api_key.access_token %></td>
                    <td><%= boolean_check_mark(api_key.access_only_with_token) %></td>
                    <td><%= api_key.note %></td>
                    <td class="table-actions">
                      <%= render 'shared/action_icons', locals: {target: api_key} %>
                    </td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>
          <div class="widget-footer">
            <%= render 'shared/pagination', locals: {target: @api_keys, model_index_path: api_keys_path} %>
          </div>
        </div>
      </div>
    </article>
  </div>
</section>

app/views/api_keys/new.html.erb
<%= render 'form' %>

app/views/api_keys/show.html.erb
<section id="widget-grid">
  <article class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
    <div id="wid-id-0" data-widget-colorbutton="false" data-widget-deletebutton="false" data-widget-editbutton="false" data-widget-togglebutton="false" class="jarviswidget jarviswidget-color-darken">
      <header><span class="widget-icon"><i class="fa fa-binoculars"></i></span>

        <div class="widget-toolbar">
          <%= link_to raw("<i class='fa fa-arrow-left'></i> #{t('simple_form.buttons.list')}"), api_keys_path, class: 'btn btn-primary' %>
          <%= link_to raw("<i class='fa fa-pencil'></i> #{t('simple_form.buttons.edit')}"), edit_api_key_path(@api_key), class: 'btn btn-primary' if can?(:update, ApiKey) %>
        </div>
      </header>
      <div>
        <!-- widget content -->
        <div class="widget-body">

          <table class="table table-striped table-hover grey-blue-table" width="100%" cellspacing="0" id="dt_basic">
            <thead>
            <tr class="hidden">
              <th></th>
              <th></th>
            </tr>
            </thead>
            <!-- el thead es necesario para que datatable no de error -->
            <tbody>
            <tr role="row">
              <th><%= t('simple_form.labels.defaults.application') %></th>
              <td>
                <%= @api_key.application %>
              </td>
            </tr>
            <tr role="row">
              <th><%= t('simple_form.labels.defaults.access_token') %></th>
              <td>
                <%= @api_key.access_token %>
              </td>
            </tr>
            <tr role="row">
              <th><%= t('simple_form.labels.defaults.access_only_with_token') %></th>
              <td>
                <%= boolean_check_mark(@api_key.access_only_with_token) %>
              </td>
            </tr>
            <tr role="row">
              <th><%= t('simple_form.labels.defaults.note') %></th>
              <td>
                <%= @api_key.note %>
              </td>
            </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </article>

  <!--
  <article class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
    <div id="wid-id-1" data-widget-colorbutton="false" data-widget-deletebutton="false" data-widget-editbutton="false" data-widget-togglebutton="false" class="jarviswidget jarviswidget-color-darken">
      <header><span class="widget-icon"><i class="fa fa-info"></i></span>
        <h2>Details</h2>
      </header>
      <div class="no-padding">
        <div class="widget-body">

        </div>
      </div>
    </div>
  </article>
  -->
</section>